# Generated by Django 4.2.4 on 2023-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("graduation", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Users",
                "managed": False,
            },
        ),
    ]
