# Generated by Django 4.2.4 on 2023-09-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("event_name", models.CharField(max_length=100)),
                ("college_name", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "cfc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CLT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("event_name", models.CharField(max_length=100)),
                ("college_name", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("prize_won", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "clt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IIPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "iipc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SCD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("event_name", models.CharField(max_length=100)),
                ("college_name", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("prize_won", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "scd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("graduation", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Users",
                "managed": False,
            },
        ),
    ]
