# Generated by Django 4.2.4 on 2023-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SRI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("club", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sri",
                "managed": False,
            },
        ),
    ]
